config/routes.rb
CarpoolOrganizer::Application.routes.draw do
  root 'welcome#index'

  resources :trips

end

app/models/drivership.rb
class Drivership < ActiveRecord::Base
  has_one :participation, as: :role, dependent: :destroy
end

app/models/participation.rb
class Participation < ActiveRecord::Base
  belongs_to :trip
  belongs_to :user
  belongs_to :role, polymorphic: true
end

app/models/passengership.rb
class Passengership < ActiveRecord::Base
  has_one :participation, as: :role, dependent: :destroy
  belongs_to :driver, foreign_key: 'driver_id'
end

app/models/trip.rb
class Trip < ActiveRecord::Base
  has_many :driverships, dependent: :destroy
  has_many :drivers, class_name: 'User', through: :driverships
  has_many :passengerships, dependent: :destroy
  has_many :passengers, class_name: 'User', through: :passengerships
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :set_trip, only: [:show, :edit, :update, :destroy]

  # GET /trips
  # GET /trips.json
  def index
    @trips = Trip.all
  end

  # GET /trips/1
  # GET /trips/1.json
  def show
  end

  # GET /trips/new
  def new
    @trip = Trip.new
  end

  # GET /trips/1/edit
  def edit
  end

  # POST /trips
  # POST /trips.json
  def create
    @trip = Trip.new(trip_params)

    respond_to do |format|
      if @trip.save
        format.html { redirect_to @trip, notice: 'Trip was successfully created.' }
        format.json { render action: 'show', status: :created, location: @trip }
      else
        format.html { render action: 'new' }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trips/1
  # PATCH/PUT /trips/1.json
  def update
    respond_to do |format|
      if @trip.update(trip_params)
        format.html { redirect_to @trip, notice: 'Trip was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trips/1
  # DELETE /trips/1.json
  def destroy
    @trip.destroy
    respond_to do |format|
      format.html { redirect_to trips_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trip
      @trip = Trip.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trip_params
      params[:trip]
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CarpoolOrganizer</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/trips/_form.html.haml
= form_for @trip do |f|
  - if @trip.errors.any?
    #error_explanation
      %h2= "#{pluralize(@trip.errors.count, "error")} prohibited this trip from being saved:"
      %ul
        - @trip.errors.full_messages.each do |msg|
          %li= msg
  = f.label :name
  = f.text_field :name
  %br
  = f.label :arrival
  = datetime_select 'trip', 'arrival'
  %br
  = f.label :public
  = f.select :public, [true, false]

  .actions
    = f.submit 'Save'

app/views/trips/edit.html.haml
%h1 Editing trip

= render 'form'

= link_to 'Show', @trip
\|
= link_to 'Back', trips_path

app/views/trips/index.html.haml
%h1 Listing trips

%table
  %tr
    %th
    %th
    %th

  - @trips.each do |trip|
    %tr
      %td= link_to 'Show', trip
      %td= link_to 'Edit', edit_trip_path(trip)
      %td= link_to 'Destroy', trip, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Trip', new_trip_path

app/views/trips/new.html.haml
%h1 New trip

= render 'form'

= link_to 'Back', trips_path

app/views/trips/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_trip_path(@trip)
\|
= link_to 'Back', trips_path

app/views/welcome/index.haml
%h2 Hello World
%p The time is now: #{ Time.now }